# Generated by Django 4.2.4 on 2023-09-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontuserbase',
            old_name='customer_id',
            new_name='id',
        ),
    ]
