# Generated by Django 4.2.4 on 2023-09-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0003_alter_frontuserbase_vip_type_alter_frontuserbase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontuserbase',
            name='call_count',
            field=models.IntegerField(blank=True, default='0', help_text='接口调用次数', null=True, verbose_name='接口调用次数'),
        ),
    ]
