# Generated by Django 4.2.4 on 2023-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0005_alter_frontuserbase_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='biz_type',
            field=models.IntegerField(choices=[(10, '注册认证'), (11, '找回密码认证')], default=10, help_text='注册认证', verbose_name='验证码过期时间'),
        ),
        migrations.AlterField(
            model_name='frontuserbase',
            name='VIP_TYPE',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, 'vip付费用户')], default=0, help_text='用户类型', verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='frontuserextraemail',
            name='verified',
            field=models.IntegerField(choices=[(0, 'unverified'), (1, 'verified')], default=0, help_text='是否验证 0 否 1 是', verbose_name='是否验证'),
        ),
        migrations.AlterField(
            model_name='sysemailsendlog',
            name='biz_type',
            field=models.IntegerField(choices=[(10, '注册认证'), (11, '找回密码认证')], default=10, help_text='认证类型', verbose_name='认证类型'),
        ),
        migrations.AlterField(
            model_name='sysemailsendlog',
            name='status',
            field=models.IntegerField(choices=[(1, '发送成功'), (0, '发送失败')], default=0, help_text='发送状态，0失败，1成功', verbose_name='发送状态'),
        ),
    ]
