# Generated by Django 4.2.4 on 2024-01-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0006_alter_emailverifycode_biz_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifycode',
            name='biz_type',
            field=models.IntegerField(choices=[(10, '注册认证'), (11, '密码重置认证')], default=10, help_text='验证码类型', verbose_name='验证码类型'),
        ),
    ]
