# Generated by Django 4.2.4 on 2024-03-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0007_alter_emailverifycode_biz_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baseUserId', models.IntegerField(blank=True, help_text='签到用户', null=True, verbose_name='用户ID')),
                ('benefits_tokens', models.IntegerField(blank=True, help_text='签到赠送tokens', null=True, verbose_name='签到赠送tokens')),
                ('benefits_dalle', models.IntegerField(blank=True, help_text='签到赠送dall-e-2,3', null=True, verbose_name='签到赠送dalle')),
                ('check_in_date', models.DateField(auto_now_add=True, help_text='签到日期', null=True, verbose_name='签到日期')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='签到时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户签到表',
                'verbose_name_plural': '用户签到表',
                'db_table': 'front_user_check_in',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
