# Generated by Django 4.2.4 on 2024-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0008_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBenefits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baseUserId', models.IntegerField(blank=True, help_text='用户ID', null=True, verbose_name='用户ID')),
                ('total_benefits_tokens', models.IntegerField(blank=True, default=2000, help_text='累计赠送tokens', null=True, verbose_name='累计赠送tokens')),
                ('total_benefits_dalle', models.IntegerField(blank=True, default=2, help_text='累计dalle-2,3', null=True, verbose_name='累计赠送dalle')),
                ('left_tokens', models.IntegerField(blank=True, default=2000, help_text='剩余tokens', null=True, verbose_name='剩余tokens')),
                ('left_dalle', models.IntegerField(blank=True, default=2, help_text='剩余dalle-2,3', null=True, verbose_name='剩余dalle')),
                ('benefits_source', models.IntegerField(choices=[(1, '兑换'), (0, '签到')], default=0, help_text='福利来源,0:签到,1:兑换', verbose_name='福利来源')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户福利表',
                'verbose_name_plural': '用户福利表',
                'db_table': 'front_user_benefits',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='UserRedeem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baseUserId', models.IntegerField(blank=True, help_text='用户ID', null=True, verbose_name='用户ID')),
                ('redeem_code', models.CharField(blank=True, help_text='兑换卡密', max_length=32, null=True, verbose_name='兑换卡密')),
                ('redeem_tokens', models.IntegerField(blank=True, default=2000, help_text='兑换赠送tokens', null=True, verbose_name='兑换赠送tokens')),
                ('redeem_dalle', models.IntegerField(blank=True, default=2, help_text='兑换赠送dall-e-2,3', null=True, verbose_name='兑换赠送dalle')),
                ('verified', models.IntegerField(choices=[(0, '未验证'), (1, '已验证')], default=0, help_text='是否验证 0 未验证 1 已验证', verbose_name='是否验证')),
                ('expire_at', models.DateTimeField(blank=True, help_text='兑换卡密过期时间', null=True, verbose_name='兑换卡密过期时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='签到时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户卡密兑换表',
                'verbose_name_plural': '用户卡密兑换表',
                'db_table': 'front_user_redeem',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.AlterField(
            model_name='checkin',
            name='benefits_dalle',
            field=models.IntegerField(blank=True, default=2, help_text='签到赠送dall-e-2,3', null=True, verbose_name='签到赠送dalle'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='benefits_tokens',
            field=models.IntegerField(blank=True, default=2000, help_text='签到赠送tokens', null=True, verbose_name='签到赠送tokens'),
        ),
    ]
