# Generated by Django 4.2.4 on 2024-03-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0009_userbenefits_userredeem_alter_checkin_benefits_dalle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userredeem',
            name='redeem_dalle',
            field=models.IntegerField(blank=True, default=10, help_text='兑换赠送dall-e-2,3', null=True, verbose_name='兑换赠送dalle'),
        ),
        migrations.AlterField(
            model_name='userredeem',
            name='redeem_tokens',
            field=models.IntegerField(blank=True, default=200000, help_text='兑换赠送tokens', null=True, verbose_name='兑换赠送tokens'),
        ),
    ]
